name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - v4
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: public
 
      - name: Upload coverage report artifact
        id: upload-artifact
        uses: actions/upload-pages-artifact@main
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        id: deployment
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/deploy-pages@v4
        env:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        with: 
          artifact_name: github-pages
          token: ${{ github.token }}
          preview: true